/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a query-language query (deterministic, no LLM). */
        post: operations["queryGraph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a deterministic graph query for an Anyshift project */
        post: operations["queryProjectGraph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a natural-language graph question. */
        post: operations["askGraph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a natural-language graph question for an Anyshift project */
        post: operations["askProjectGraph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "unauthorized" | "bad_request" | "project_required" | "forbidden" | "not_found" | "payload_too_large" | "timeout" | "project_graph_unconfigured" | "project_events_graph_unconfigured" | "internal";
                message: string;
            };
        };
        QueryRequest: {
            /** @description SELECT <*|count(*)> FROM <table> [WHERE k = v [AND ...]] [LIMIT n] [OFFSET n] */
            sql: string;
        };
        AskRequest: {
            /** @description Natural-language graph question */
            question: string;
        };
        Page: {
            limit: number;
            offset: number;
            hasMore: boolean;
            nextOffset: number | null;
        };
        GraphNode: {
            id: string;
            anyshiftID: string | null;
            name: string;
            type: string | null;
            namespace: string | null;
            image?: string | null;
        };
        GraphEdge: {
            from: string;
            to: string;
            type: string;
            /** @enum {string} */
            direction: "upstream" | "downstream";
        };
        ResolveResult: {
            term: string;
            candidates: {
                id: string;
                anyshiftID: string | null;
                name: string;
                type: string | null;
                namespace: string | null;
                cluster: string | null;
            }[];
        };
        InventoryResult: {
            type: string;
            total: number;
            byNamespace: {
                namespace: string;
                count: number;
            }[];
            sample: {
                name: string;
                namespace: string | null;
                resourceId: string | null;
            }[];
            availableTypes: {
                label: string;
                count: number;
            }[];
            page: {
                limit: number;
                offset: number;
                hasMore: boolean;
                nextOffset: number | null;
            };
        };
        EventsResult: {
            filter: {
                eventType: string;
                target: string;
                namespace: string;
                includeNoise: boolean;
            };
            total: number;
            byType: {
                type: string;
                count: number;
            }[];
            recent: {
                ts: string;
                type: string;
                summary: string | null;
                targetKind: string | null;
                target: string | null;
                namespace: string | null;
                isRoot: boolean;
                noiseClass: string | null;
                cluster: string | null;
            }[];
            page: {
                limit: number;
                offset: number;
                hasMore: boolean;
                nextOffset: number | null;
            };
        };
        HotspotsResult: {
            /** @enum {string} */
            dimension: "namespace" | "resource" | "alertrule" | "alertworkload";
            filter: {
                eventType: string;
                namespace: string;
                includeNoise: boolean;
            };
            ranking: {
                key: string;
                total: number;
                namespace: string | null;
                recovers?: number;
                flap?: number;
            }[];
        };
        IncidentResult: {
            correlationId: string | null;
            total: number;
            roots: number;
            namespaces: string[];
            byType: {
                type: string;
                count: number;
            }[];
            rootCauses: {
                ts: string;
                type: string;
                summary: string | null;
                targetKind: string | null;
                target: string | null;
                namespace: string | null;
                isRoot: boolean;
                noiseClass: string | null;
                cluster: string | null;
            }[];
            chain: {
                ts: string;
                type: string;
                summary: string | null;
                targetKind: string | null;
                target: string | null;
                namespace: string | null;
                isRoot: boolean;
                noiseClass: string | null;
                cluster: string | null;
            }[];
        };
        EventFeedResult: {
            filter: {
                target: string;
                sinceHours: number | null;
            };
            total: number;
            byType: {
                type: string;
                count: number;
            }[];
            recent: {
                ts: string;
                type: string;
                summary: string | null;
                targetKind: string | null;
                target: string | null;
                namespace: string | null;
                isRoot: boolean;
                noiseClass: string | null;
                cluster: string | null;
            }[];
            page: {
                limit: number;
                offset: number;
                hasMore: boolean;
                nextOffset: number | null;
            };
        };
        DeploymentsResult: {
            filter: {
                target: string;
                namespace: string;
                sinceHours: number | null;
            };
            total: number;
            namespaces: string[];
            recent: {
                ts: string;
                target: string | null;
                namespace: string | null;
                images: {
                    from: string | null;
                    to: string | null;
                }[];
            }[];
            page: {
                limit: number;
                offset: number;
                hasMore: boolean;
                nextOffset: number | null;
            };
        };
        DeployImpactResult: {
            /** @enum {string} */
            scope: "ranked" | "target";
            filter: {
                target: string;
                sinceHours: number | null;
            };
            ranking: {
                deployed: string;
                namespace: string | null;
                rollouts: number;
                fallout: number;
                effects: {
                    type: string;
                    count: number;
                }[];
            }[];
            target: string;
            rollouts: number;
            total: number;
            byType: {
                type: string;
                count: number;
            }[];
            recent: {
                ts: string;
                type: string;
                summary: string | null;
                targetKind: string | null;
                target: string | null;
                namespace: string | null;
                isRoot: boolean;
                noiseClass: string | null;
                cluster: string | null;
            }[];
        };
        CommonCauseResult: {
            filter: {
                namespace: string;
                sinceHours: number | null;
            };
            failingPods: number;
            events: number;
            byNode: {
                name: string;
                namespace: string | null;
                affected: number;
            }[];
            byWorkload: {
                name: string;
                namespace: string | null;
                affected: number;
            }[];
            byDatastore: {
                name: string;
                namespace: string | null;
                affected: number;
            }[];
            byExternal: {
                name: string;
                namespace: string | null;
                affected: number;
            }[];
        };
        BlastRadiusResult: {
            pods: number;
            workloads: {
                name: string;
                namespace: string | null;
                affected: number;
            }[];
            services: {
                name: string;
                namespace: string | null;
                affected: number;
            }[];
        };
        SpofResult: {
            /** @enum {string} */
            kind: "configmap" | "serviceaccount" | "node";
            filter: {
                namespace: string;
            };
            items: {
                name: string;
                namespace: string | null;
                workloads: number;
                pods: number;
            }[];
        };
        PathResult: {
            from: {
                term: string;
                name: string;
                type: string | null;
            } | null;
            to: {
                term: string;
                name: string;
                type: string | null;
            } | null;
            found: boolean;
            hops: number;
            chain: {
                name: string;
                type: string | null;
                namespace: string | null;
            }[];
            rels: string[];
        };
        CascadeResult: {
            correlationId: string;
            root: {
                ts: string;
                type: string;
                kind: string | null;
                target: string | null;
                namespace: string | null;
            } | null;
            totalEvents: number;
            spanSeconds: number;
            byReason: {
                reason: string;
                count: number;
            }[];
            steps: {
                resource: string;
                namespace: string | null;
                firstType: string;
                reason: string | null;
                events: number;
                offsetSeconds: number;
            }[];
        };
        AlertImpactResult: {
            scope: string;
            workloads: number;
            services: number;
            counts: {
                monitors: number;
                slos: number;
            };
            monitors: {
                name: string;
                service: string | null;
            }[];
            slos: {
                name: string;
                service: string | null;
            }[];
        };
        MonitorResult: {
            term: string;
            matched: number;
            monitors: string[];
            services: string[];
            workloads: {
                name: string;
                type: string | null;
                namespace: string | null;
            }[];
            nodes: string[];
            slos: string[];
        };
        DataStoreResult: {
            /** @enum {string} */
            scope: "ranked" | "target";
            ranking: {
                name: string;
                services: number;
            }[];
            target: {
                name: string;
                services: number;
                sample: string[];
            } | null;
        };
        FlowResult: {
            /** @enum {string} */
            scope: "ranked" | "target";
            ranking: {
                name: string;
                producers: number;
                consumers: number;
            }[];
            target: {
                name: string;
                producers: string[];
                consumers: string[];
            } | null;
        };
        ExternalDepResult: {
            /** @enum {string} */
            scope: "ranked" | "target";
            ranking: {
                name: string;
                services: number;
            }[];
            target: {
                name: string;
                services: number;
                sample: string[];
            } | null;
        };
        AlertsResult: {
            filter: {
                target: string;
            };
            total: number;
            byState: {
                state: string;
                count: number;
            }[];
            firing: {
                monitor: string;
                state: string;
                service: string | null;
                workload: string | null;
                namespace: string | null;
            }[];
        };
        AlertNoiseResult: {
            /** @enum {string} */
            scope: "ranked" | "target";
            filter: {
                noiseKind: string;
                window: string;
            };
            target: string | null;
            monitors: {
                name: string;
                fires: number;
                recovers: number;
                pctSelfResolved: number;
                /** @enum {string} */
                noiseKind: "flapping" | "stuck";
            }[];
            counts: {
                flapping: number;
                stuck: number;
                totalFires: number;
            };
        };
        CallsResult: {
            /** @enum {string} */
            scope: "ranked" | "target";
            ranking: {
                name: string;
                callers: number;
            }[];
            target: {
                name: string;
                callerCount: number;
                calleeCount: number;
                callers: string[];
                callees: string[];
            } | null;
        };
        ServiceTreeResult: {
            /** @enum {string} */
            scope: "ranked" | "target";
            ranking: {
                name: string;
                serviceCount: number;
                leafCount: number;
                footprint: number;
            }[];
            target: {
                name: string;
                serviceCount: number;
                datastoreCount: number;
                externalCount: number;
                services: string[];
                datastores: string[];
                externals: string[];
                hasCycle: boolean;
            } | null;
        };
        AlertCauseResult: {
            target: string;
            workload: string | null;
            namespace: string | null;
            firingMonitors: string[];
            firingCount: number;
            changes: {
                ts: string;
                type: string;
                summary: string | null;
                target: string | null;
            }[];
        };
        AccessResult: {
            /** @enum {string} */
            mode: "reach" | "privileged";
            /** @enum {string} */
            direction: "subject" | "object";
            serviceAccounts: string[];
            roles: {
                role: string;
                namespace: string | null;
                via: string | null;
                cluster: boolean;
                rules: {
                    verbs: string[];
                    resources: string[];
                    apiGroups: string[];
                }[];
                privileged: boolean;
                reasons: string[];
            }[];
            subjects: {
                serviceAccount: string;
                namespace: string | null;
                via: string | null;
                pods: number;
                workloads: string[];
            }[];
            privileged: {
                serviceAccount: string;
                namespace: string | null;
                pods: number;
                workloads: string[];
                score: number;
                reasons: string[];
                roles: {
                    role: string;
                    namespace: string | null;
                    via: string | null;
                    cluster: boolean;
                    rules: {
                        verbs: string[];
                        resources: string[];
                        apiGroups: string[];
                    }[];
                    privileged: boolean;
                    reasons: string[];
                }[];
            }[];
        };
        ExposureResult: {
            /** @enum {string} */
            direction: "ingress" | "workload";
            exposed: boolean;
            services: {
                service: string;
                namespace: string | null;
                pods: number;
                workloads: string[];
            }[];
            ingresses: {
                ingress: string;
                namespace: string | null;
                via: string | null;
            }[];
        };
        OrphansResult: {
            /** @enum {string} */
            kind: "configmap" | "serviceaccount" | "role" | "replicaset";
            filter: {
                namespace: string;
            };
            items: {
                name: string;
                namespace: string | null;
            }[];
        };
        CoverageResult: {
            /** @enum {string} */
            kind: "service" | "monitor" | "metrics";
            filter: {
                namespace: string;
            };
            items: {
                name: string;
                namespace: string | null;
                kind: string | null;
            }[];
        };
        SloResult: {
            /** @enum {string} */
            scope: "ranked" | "target";
            ranking: {
                name: string;
                status: string;
                alerting: number;
                warning: number;
                monitors: number;
            }[];
            target: {
                name: string;
                status: string;
                alerting: number;
                warning: number;
                monitors: number;
                sample: {
                    name: string;
                    state: string;
                    service: string | null;
                }[];
            } | null;
        };
        TenancyResult: {
            nodes: string[];
            ownPods: number;
            neighbors: {
                name: string;
                namespace: string | null;
                type: string | null;
                pods: number;
                nodes: string[];
            }[];
        };
        SharedConfigResult: {
            configmaps: string[];
            ownPods: number;
            siblings: {
                name: string;
                namespace: string | null;
                type: string | null;
                pods: number;
                configmaps: string[];
            }[];
        };
        AlertRulesResult: {
            /** @enum {string} */
            subject: "coverage" | "inventory" | "target";
            filter: {
                namespace: string;
                term: string;
            };
            coverage: {
                name: string;
                namespace: string | null;
                kind: string;
                replicas: number;
                hasHpa: boolean;
                exposed: boolean;
            }[];
            inventory: {
                name: string;
                uid: string | null;
                ruleGroup: string | null;
                alerts: number;
                watched: number;
                severities: string[];
            }[];
            target: {
                name: string;
                namespace: string | null;
                kind: string;
                rules: string[];
                datastores: string[];
                destinations: string[];
            } | null;
        };
        GitopsResult: {
            /** @enum {string} */
            subject: "drift" | "unmanaged" | "owner";
            filter: {
                namespace: string;
            };
            drift: {
                name: string;
                syncStatus: string | null;
                healthStatus: string | null;
                repoUrl: string | null;
                sourcePath: string | null;
            }[];
            unmanaged: {
                name: string;
                namespace: string | null;
                kind: string;
            }[];
            owner: {
                workload: string;
                namespace: string | null;
                application: string | null;
                repoUrl: string | null;
                sourcePath: string | null;
                targetRevision: string | null;
                syncStatus: string | null;
                healthStatus: string | null;
            } | null;
        };
        ImageResult: {
            /** @enum {string} */
            mode: "ranked" | "byimage" | "workload" | "hygiene";
            ranking: {
                image: string;
                containers: number;
                pods: number;
            }[];
            byImage: {
                term: string;
                matchedImages: string[];
                containers: number;
                pods: number;
                workloadCount: number;
                workloads: {
                    name: string;
                    namespace: string | null;
                    kind: string | null;
                }[];
            } | null;
            workload: {
                name: string;
                type: string | null;
                namespace: string | null;
                imageCount: number;
                containers: {
                    name: string | null;
                    image: string;
                    isInit: boolean;
                    cpuRequest: string | null;
                    memRequest: string | null;
                    memLimit: string | null;
                    pod: string | null;
                }[];
            } | null;
            hygiene: {
                /** @enum {string} */
                kind: "nomemlimit" | "nocpurequest" | "skew";
                items: {
                    workload: string;
                    namespace: string | null;
                    container: string | null;
                    image: string;
                    detail: string | null;
                }[];
            } | null;
        };
        NetpolResult: {
            /** @enum {string} */
            mode: "uncovered" | "policy" | "segmentation";
            filter: {
                namespace: string;
                term: string;
            };
            uncovered: {
                namespace: string;
                pods: number;
                workloads: string[];
            }[];
            covered: boolean;
            ingressCovered: boolean;
            policies: {
                name: string;
                namespace: string | null;
                policyTypes: string[];
                ingressRuleCount: number;
                egressRuleCount: number;
                podSelector: string | null;
            }[];
            reachers: {
                name: string;
                namespace: string | null;
                type: string | null;
                pods: number;
            }[];
        };
        StorageResult: {
            /** @enum {string} */
            mode: "footprint" | "orphanpv" | "unclaimedpvc" | "byclass";
            filter: {
                term: string;
            };
            claims: {
                pvc: string;
                pvcNamespace: string | null;
                pv: string | null;
                storageClass: string | null;
                capacity: string | null;
                pods: string[];
            }[];
            orphanPvs: {
                name: string;
                storageClass: string | null;
                capacity: string | null;
                reclaimPolicy: string | null;
            }[];
            unclaimedPvcs: {
                name: string;
                namespace: string | null;
                pv: string | null;
                storageClass: string | null;
            }[];
            classes: {
                name: string;
                pvs: number;
                pvcs: number;
            }[];
        };
        PdbResult: {
            /** @enum {string} */
            scope: "nopdb" | "workload" | "pdb";
            items: {
                name: string;
                namespace: string | null;
                kind: string | null;
            }[];
            workload: {
                totalPods: number;
                protectedPods: number;
                pdbs: string[];
            } | null;
            pdb: {
                pods: number;
                podSample: string[];
                workloads: string[];
            } | null;
        };
        ScalingResult: {
            /** @enum {string} */
            mode: "nohpa" | "autoscaled" | "target";
            filter: {
                namespace: string;
                term: string;
            };
            items: {
                name: string;
                namespace: string | null;
                kind: string | null;
                replicas: number | null;
                hpa: string | null;
                minReplicas: number | null;
                maxReplicas: number | null;
            }[];
            target: {
                name: string;
                namespace: string | null;
                resolvedKind: string | null;
                minReplicas: number | null;
                maxReplicas: number | null;
                hpas: {
                    name: string;
                    namespace: string | null;
                    minReplicas: number | null;
                    maxReplicas: number | null;
                }[];
                scales: {
                    name: string;
                    namespace: string | null;
                    kind: string | null;
                }[];
            } | null;
        };
        TopologyResult: {
            resolved: {
                term: string;
                service: string;
            } | null;
            /** @enum {string} */
            level: "context" | "container" | "component" | "dynamic";
            nodeCount: number;
            edgeCount: number;
            byType: {
                type: string;
                count: number;
            }[];
        };
        PriorityResult: {
            /** @enum {string} */
            kind: "nopriority" | "ladder" | "target";
            filter: {
                namespace: string;
                term: string;
            };
            nopriority: {
                name: string;
                namespace: string | null;
                kind: string;
                pods: number;
            }[];
            ladder: {
                name: string;
                value: number;
                pods: number;
            }[];
            classes: {
                name: string;
                value: number;
                pods: number;
            }[];
        };
        AskResult: {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "resolve";
            resolve: components["schemas"]["ResolveResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "connections";
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "inventory";
            inventory: components["schemas"]["InventoryResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "events";
            events: components["schemas"]["EventsResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "hotspots";
            hotspots: components["schemas"]["HotspotsResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "incident";
            incident: components["schemas"]["IncidentResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "failures";
            failures: components["schemas"]["EventFeedResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "deployments";
            deployments: components["schemas"]["DeploymentsResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "audit";
            audit: components["schemas"]["EventFeedResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "nodes";
            nodeEvents: components["schemas"]["EventFeedResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "deployimpact";
            deployImpact: components["schemas"]["DeployImpactResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "commoncause";
            commonCause: components["schemas"]["CommonCauseResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "blast";
            blastRadius: components["schemas"]["BlastRadiusResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "spof";
            spof: components["schemas"]["SpofResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "path";
            path: components["schemas"]["PathResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "cascade";
            cascade: components["schemas"]["CascadeResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "alertimpact";
            alertImpact: components["schemas"]["AlertImpactResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "monitor";
            monitor: components["schemas"]["MonitorResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "datastore";
            dataStore: components["schemas"]["DataStoreResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "flow";
            flow: components["schemas"]["FlowResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "externaldep";
            externalDep: components["schemas"]["ExternalDepResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "alerts";
            alerts: components["schemas"]["AlertsResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "alertnoise";
            alertNoise: components["schemas"]["AlertNoiseResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "calls";
            calls: components["schemas"]["CallsResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "servicetree";
            serviceTree: components["schemas"]["ServiceTreeResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "alertcause";
            alertCause: components["schemas"]["AlertCauseResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "access";
            access: components["schemas"]["AccessResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "exposure";
            exposure: components["schemas"]["ExposureResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "orphans";
            orphans: components["schemas"]["OrphansResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "coverage";
            coverage: components["schemas"]["CoverageResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "slo";
            slo: components["schemas"]["SloResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "tenancy";
            tenancy: components["schemas"]["TenancyResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "sharedconfig";
            sharedConfig: components["schemas"]["SharedConfigResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "alertrules";
            alertRules: components["schemas"]["AlertRulesResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "gitops";
            gitops: components["schemas"]["GitopsResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "image";
            image: components["schemas"]["ImageResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "netpol";
            netpol: components["schemas"]["NetpolResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "storage";
            storage: components["schemas"]["StorageResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "pdb";
            pdb: components["schemas"]["PdbResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "scaling";
            scaling: components["schemas"]["ScalingResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "topology";
            topology: components["schemas"]["TopologyResult"] | null;
        } | {
            question: string;
            summary: string;
            countOnly?: boolean;
            elapsedMs?: number;
            resolved?: {
                term: string;
                hashedID: string;
                name: string;
                type: string | null;
            } | null;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            /** @constant */
            intent: "priority";
            priority: components["schemas"]["PriorityResult"] | null;
        };
    };
    responses: never;
    parameters: {
        /** @description Anyshift project id whose graph should be queried. */
        ProjectId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    queryGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResult"];
                };
            };
            /** @description Bad query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Query timed out */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    queryProjectGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Anyshift project id whose graph should be queried. */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Query result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Project events graph unconfigured or internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Query timed out */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    askGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Query timed out */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    askProjectGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Anyshift project id whose graph should be queried. */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Project events graph unconfigured or internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Query timed out */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
