// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package openapi

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AskResultIntent.
const (
	Access       AskResultIntent = "access"
	Alertcause   AskResultIntent = "alertcause"
	Alertimpact  AskResultIntent = "alertimpact"
	Alertnoise   AskResultIntent = "alertnoise"
	Alertrules   AskResultIntent = "alertrules"
	Alerts       AskResultIntent = "alerts"
	Audit        AskResultIntent = "audit"
	Blast        AskResultIntent = "blast"
	Calls        AskResultIntent = "calls"
	Cascade      AskResultIntent = "cascade"
	Commoncause  AskResultIntent = "commoncause"
	Connections  AskResultIntent = "connections"
	Coverage     AskResultIntent = "coverage"
	Datastore    AskResultIntent = "datastore"
	Deployimpact AskResultIntent = "deployimpact"
	Deployments  AskResultIntent = "deployments"
	Events       AskResultIntent = "events"
	Exposure     AskResultIntent = "exposure"
	Externaldep  AskResultIntent = "externaldep"
	Failures     AskResultIntent = "failures"
	Flow         AskResultIntent = "flow"
	Gitops       AskResultIntent = "gitops"
	Hotspots     AskResultIntent = "hotspots"
	Image        AskResultIntent = "image"
	Incident     AskResultIntent = "incident"
	Inventory    AskResultIntent = "inventory"
	Monitor      AskResultIntent = "monitor"
	Netpol       AskResultIntent = "netpol"
	Nodes        AskResultIntent = "nodes"
	Orphans      AskResultIntent = "orphans"
	Path         AskResultIntent = "path"
	Pdb          AskResultIntent = "pdb"
	Priority     AskResultIntent = "priority"
	Scaling      AskResultIntent = "scaling"
	Servicetree  AskResultIntent = "servicetree"
	Sharedconfig AskResultIntent = "sharedconfig"
	Slo          AskResultIntent = "slo"
	Spof         AskResultIntent = "spof"
	Storage      AskResultIntent = "storage"
	Tenancy      AskResultIntent = "tenancy"
	Topology     AskResultIntent = "topology"
)

// Valid indicates whether the value is a known member of the AskResultIntent enum.
func (e AskResultIntent) Valid() bool {
	switch e {
	case Access:
		return true
	case Alertcause:
		return true
	case Alertimpact:
		return true
	case Alertnoise:
		return true
	case Alertrules:
		return true
	case Alerts:
		return true
	case Audit:
		return true
	case Blast:
		return true
	case Calls:
		return true
	case Cascade:
		return true
	case Commoncause:
		return true
	case Connections:
		return true
	case Coverage:
		return true
	case Datastore:
		return true
	case Deployimpact:
		return true
	case Deployments:
		return true
	case Events:
		return true
	case Exposure:
		return true
	case Externaldep:
		return true
	case Failures:
		return true
	case Flow:
		return true
	case Gitops:
		return true
	case Hotspots:
		return true
	case Image:
		return true
	case Incident:
		return true
	case Inventory:
		return true
	case Monitor:
		return true
	case Netpol:
		return true
	case Nodes:
		return true
	case Orphans:
		return true
	case Path:
		return true
	case Pdb:
		return true
	case Priority:
		return true
	case Scaling:
		return true
	case Servicetree:
		return true
	case Sharedconfig:
		return true
	case Slo:
		return true
	case Spof:
		return true
	case Storage:
		return true
	case Tenancy:
		return true
	case Topology:
		return true
	default:
		return false
	}
}

// Defines values for CallsResultScope.
const (
	CallsResultScopeRanked CallsResultScope = "ranked"
	CallsResultScopeTarget CallsResultScope = "target"
)

// Valid indicates whether the value is a known member of the CallsResultScope enum.
func (e CallsResultScope) Valid() bool {
	switch e {
	case CallsResultScopeRanked:
		return true
	case CallsResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for DataStoreResultScope.
const (
	DataStoreResultScopeRanked DataStoreResultScope = "ranked"
	DataStoreResultScopeTarget DataStoreResultScope = "target"
)

// Valid indicates whether the value is a known member of the DataStoreResultScope enum.
func (e DataStoreResultScope) Valid() bool {
	switch e {
	case DataStoreResultScopeRanked:
		return true
	case DataStoreResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for DeployImpactResultScope.
const (
	DeployImpactResultScopeRanked DeployImpactResultScope = "ranked"
	DeployImpactResultScopeTarget DeployImpactResultScope = "target"
)

// Valid indicates whether the value is a known member of the DeployImpactResultScope enum.
func (e DeployImpactResultScope) Valid() bool {
	switch e {
	case DeployImpactResultScopeRanked:
		return true
	case DeployImpactResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeErrorCode.
const (
	BadRequest                     ErrorEnvelopeErrorCode = "bad_request"
	Forbidden                      ErrorEnvelopeErrorCode = "forbidden"
	Internal                       ErrorEnvelopeErrorCode = "internal"
	NotFound                       ErrorEnvelopeErrorCode = "not_found"
	PayloadTooLarge                ErrorEnvelopeErrorCode = "payload_too_large"
	ProjectEventsGraphUnconfigured ErrorEnvelopeErrorCode = "project_events_graph_unconfigured"
	ProjectGraphUnconfigured       ErrorEnvelopeErrorCode = "project_graph_unconfigured"
	ProjectRequired                ErrorEnvelopeErrorCode = "project_required"
	Timeout                        ErrorEnvelopeErrorCode = "timeout"
	Unauthorized                   ErrorEnvelopeErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorCode enum.
func (e ErrorEnvelopeErrorCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case Forbidden:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case PayloadTooLarge:
		return true
	case ProjectEventsGraphUnconfigured:
		return true
	case ProjectGraphUnconfigured:
		return true
	case ProjectRequired:
		return true
	case Timeout:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for ExternalDepResultScope.
const (
	ExternalDepResultScopeRanked ExternalDepResultScope = "ranked"
	ExternalDepResultScopeTarget ExternalDepResultScope = "target"
)

// Valid indicates whether the value is a known member of the ExternalDepResultScope enum.
func (e ExternalDepResultScope) Valid() bool {
	switch e {
	case ExternalDepResultScopeRanked:
		return true
	case ExternalDepResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for FlowResultScope.
const (
	FlowResultScopeRanked FlowResultScope = "ranked"
	FlowResultScopeTarget FlowResultScope = "target"
)

// Valid indicates whether the value is a known member of the FlowResultScope enum.
func (e FlowResultScope) Valid() bool {
	switch e {
	case FlowResultScopeRanked:
		return true
	case FlowResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for GraphEdgeDirection.
const (
	Downstream GraphEdgeDirection = "downstream"
	Upstream   GraphEdgeDirection = "upstream"
)

// Valid indicates whether the value is a known member of the GraphEdgeDirection enum.
func (e GraphEdgeDirection) Valid() bool {
	switch e {
	case Downstream:
		return true
	case Upstream:
		return true
	default:
		return false
	}
}

// Defines values for ServiceTreeResultScope.
const (
	ServiceTreeResultScopeRanked ServiceTreeResultScope = "ranked"
	ServiceTreeResultScopeTarget ServiceTreeResultScope = "target"
)

// Valid indicates whether the value is a known member of the ServiceTreeResultScope enum.
func (e ServiceTreeResultScope) Valid() bool {
	switch e {
	case ServiceTreeResultScopeRanked:
		return true
	case ServiceTreeResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for SloResultScope.
const (
	Ranked SloResultScope = "ranked"
	Target SloResultScope = "target"
)

// Valid indicates whether the value is a known member of the SloResultScope enum.
func (e SloResultScope) Valid() bool {
	switch e {
	case Ranked:
		return true
	case Target:
		return true
	default:
		return false
	}
}

// AccessResult defines model for AccessResult.
type AccessResult map[string]interface{}

// AlertCauseResult defines model for AlertCauseResult.
type AlertCauseResult map[string]interface{}

// AlertImpactResult defines model for AlertImpactResult.
type AlertImpactResult map[string]interface{}

// AlertNoiseResult defines model for AlertNoiseResult.
type AlertNoiseResult map[string]interface{}

// AlertRulesResult defines model for AlertRulesResult.
type AlertRulesResult map[string]interface{}

// AlertsResult defines model for AlertsResult.
type AlertsResult map[string]interface{}

// AskRequest defines model for AskRequest.
type AskRequest struct {
	Question string `json:"question"`
}

// AskResult defines model for AskResult.
type AskResult struct {
	Access       *AccessResult       `json:"access,omitempty"`
	AlertCause   *AlertCauseResult   `json:"alertCause,omitempty"`
	AlertImpact  *AlertImpactResult  `json:"alertImpact,omitempty"`
	AlertNoise   *AlertNoiseResult   `json:"alertNoise,omitempty"`
	AlertRules   *AlertRulesResult   `json:"alertRules,omitempty"`
	Alerts       *AlertsResult       `json:"alerts,omitempty"`
	Audit        *EventFeedResult    `json:"audit,omitempty"`
	BlastRadius  *BlastRadiusResult  `json:"blastRadius,omitempty"`
	Calls        *CallsResult        `json:"calls,omitempty"`
	Cascade      *CascadeResult      `json:"cascade,omitempty"`
	CommonCause  *CommonCauseResult  `json:"commonCause,omitempty"`
	CountOnly    *bool               `json:"countOnly,omitempty"`
	Coverage     *CoverageResult     `json:"coverage,omitempty"`
	DataStore    *DataStoreResult    `json:"dataStore,omitempty"`
	DeployImpact *DeployImpactResult `json:"deployImpact,omitempty"`
	Deployments  *DeploymentsResult  `json:"deployments,omitempty"`
	Edges        *[]GraphEdge        `json:"edges,omitempty"`
	ElapsedMs    *int                `json:"elapsedMs,omitempty"`
	Events       *EventsResult       `json:"events,omitempty"`
	Exposure     *ExposureResult     `json:"exposure,omitempty"`
	ExternalDep  *ExternalDepResult  `json:"externalDep,omitempty"`
	Failures     *EventFeedResult    `json:"failures,omitempty"`
	Flow         *FlowResult         `json:"flow,omitempty"`
	Gitops       *GitopsResult       `json:"gitops,omitempty"`
	Hotspots     *HotspotsResult     `json:"hotspots,omitempty"`
	Image        *ImageResult        `json:"image,omitempty"`
	Incident     *IncidentResult     `json:"incident,omitempty"`
	Intent       AskResultIntent     `json:"intent"`
	Inventory    *InventoryResult    `json:"inventory,omitempty"`
	Monitor      *MonitorResult      `json:"monitor,omitempty"`
	Netpol       *NetpolResult       `json:"netpol,omitempty"`
	NodeEvents   *EventFeedResult    `json:"nodeEvents,omitempty"`
	Nodes        *[]GraphNode        `json:"nodes,omitempty"`
	Orphans      *OrphansResult      `json:"orphans,omitempty"`
	Page         *Page               `json:"page,omitempty"`
	Path         *PathResult         `json:"path,omitempty"`
	Pdb          *PdbResult          `json:"pdb,omitempty"`
	Priority     *PriorityResult     `json:"priority,omitempty"`
	Question     string              `json:"question"`
	Resolved     *ResolvedResource   `json:"resolved,omitempty"`
	Scaling      *ScalingResult      `json:"scaling,omitempty"`
	ServiceTree  *ServiceTreeResult  `json:"serviceTree,omitempty"`
	SharedConfig *SharedConfigResult `json:"sharedConfig,omitempty"`
	Slo          *SloResult          `json:"slo,omitempty"`
	Spof         *SpofResult         `json:"spof,omitempty"`
	Storage      *StorageResult      `json:"storage,omitempty"`
	Summary      string              `json:"summary"`
	Tenancy      *TenancyResult      `json:"tenancy,omitempty"`
	Topology     *TopologyResult     `json:"topology,omitempty"`
}

// AskResultIntent defines model for AskResult.Intent.
type AskResultIntent string

// BlastRadiusResult defines model for BlastRadiusResult.
type BlastRadiusResult struct {
	Pods      int           `json:"pods"`
	Services  []SharedCause `json:"services"`
	Workloads []SharedCause `json:"workloads"`
}

// CallsResult defines model for CallsResult.
type CallsResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   CallsResultScope         `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// CallsResultScope defines model for CallsResult.Scope.
type CallsResultScope string

// CascadeResult defines model for CascadeResult.
type CascadeResult map[string]interface{}

// CommonCauseResult defines model for CommonCauseResult.
type CommonCauseResult struct {
	ByDatastore []SharedCause          `json:"byDatastore"`
	ByExternal  []SharedCause          `json:"byExternal"`
	ByNode      []SharedCause          `json:"byNode"`
	ByWorkload  []SharedCause          `json:"byWorkload"`
	Events      int                    `json:"events"`
	FailingPods int                    `json:"failingPods"`
	Filter      map[string]interface{} `json:"filter"`
}

// CountByType defines model for CountByType.
type CountByType struct {
	Count int    `json:"count"`
	Type  string `json:"type"`
}

// CoverageResult defines model for CoverageResult.
type CoverageResult struct {
	Filter map[string]interface{}   `json:"filter"`
	Items  []map[string]interface{} `json:"items"`
	Kind   string                   `json:"kind"`
}

// DataStoreResult defines model for DataStoreResult.
type DataStoreResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   DataStoreResultScope     `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// DataStoreResultScope defines model for DataStoreResult.Scope.
type DataStoreResultScope string

// DeployImpactResult defines model for DeployImpactResult.
type DeployImpactResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   DeployImpactResultScope  `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// DeployImpactResultScope defines model for DeployImpactResult.Scope.
type DeployImpactResultScope string

// DeploymentsResult defines model for DeploymentsResult.
type DeploymentsResult struct {
	Filter     map[string]interface{}   `json:"filter"`
	Namespaces []string                 `json:"namespaces"`
	Page       Page                     `json:"page"`
	Recent     []map[string]interface{} `json:"recent"`
	Total      int                      `json:"total"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code    ErrorEnvelopeErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorEnvelopeErrorCode defines model for ErrorEnvelope.Error.Code.
type ErrorEnvelopeErrorCode string

// EventFeedResult defines model for EventFeedResult.
type EventFeedResult struct {
	ByType []CountByType          `json:"byType"`
	Filter map[string]interface{} `json:"filter"`
	Page   Page                   `json:"page"`
	Recent []EventItem            `json:"recent"`
	Total  int                    `json:"total"`
}

// EventItem defines model for EventItem.
type EventItem struct {
	Cluster    *string `json:"cluster"`
	IsRoot     bool    `json:"isRoot"`
	Namespace  *string `json:"namespace"`
	NoiseClass *string `json:"noiseClass"`
	Summary    *string `json:"summary"`
	Target     *string `json:"target"`
	TargetKind *string `json:"targetKind"`
	Ts         string  `json:"ts"`
	Type       string  `json:"type"`
}

// EventsResult defines model for EventsResult.
type EventsResult struct {
	ByType []CountByType          `json:"byType"`
	Filter map[string]interface{} `json:"filter"`
	Page   Page                   `json:"page"`
	Recent []EventItem            `json:"recent"`
	Total  int                    `json:"total"`
}

// ExposureResult defines model for ExposureResult.
type ExposureResult map[string]interface{}

// ExternalDepResult defines model for ExternalDepResult.
type ExternalDepResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   ExternalDepResultScope   `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// ExternalDepResultScope defines model for ExternalDepResult.Scope.
type ExternalDepResultScope string

// FlowResult defines model for FlowResult.
type FlowResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   FlowResultScope          `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// FlowResultScope defines model for FlowResult.Scope.
type FlowResultScope string

// GitopsResult defines model for GitopsResult.
type GitopsResult map[string]interface{}

// GraphEdge defines model for GraphEdge.
type GraphEdge struct {
	Direction GraphEdgeDirection `json:"direction"`
	From      string             `json:"from"`
	To        string             `json:"to"`
	Type      string             `json:"type"`
}

// GraphEdgeDirection defines model for GraphEdge.Direction.
type GraphEdgeDirection string

// GraphNode defines model for GraphNode.
type GraphNode struct {
	AnyshiftID *string `json:"anyshiftID"`
	Id         string  `json:"id"`
	Name       string  `json:"name"`
	Namespace  *string `json:"namespace"`
	Type       *string `json:"type"`
}

// HotspotsResult defines model for HotspotsResult.
type HotspotsResult struct {
	Dimension string                   `json:"dimension"`
	Filter    map[string]interface{}   `json:"filter"`
	Ranking   []map[string]interface{} `json:"ranking"`
}

// ImageResult defines model for ImageResult.
type ImageResult map[string]interface{}

// IncidentResult defines model for IncidentResult.
type IncidentResult struct {
	ByType        []CountByType `json:"byType"`
	Chain         []EventItem   `json:"chain"`
	CorrelationId *string       `json:"correlationId"`
	Namespaces    []string      `json:"namespaces"`
	RootCauses    []EventItem   `json:"rootCauses"`
	Roots         int           `json:"roots"`
	Total         int           `json:"total"`
}

// InventoryResult defines model for InventoryResult.
type InventoryResult struct {
	AvailableTypes []map[string]interface{} `json:"availableTypes"`
	ByNamespace    []map[string]interface{} `json:"byNamespace"`
	Sample         []map[string]interface{} `json:"sample"`
	Total          int                      `json:"total"`
	Type           string                   `json:"type"`
}

// MonitorResult defines model for MonitorResult.
type MonitorResult map[string]interface{}

// NetpolResult defines model for NetpolResult.
type NetpolResult map[string]interface{}

// OrphansResult defines model for OrphansResult.
type OrphansResult struct {
	Filter map[string]interface{}   `json:"filter"`
	Items  []map[string]interface{} `json:"items"`
	Kind   string                   `json:"kind"`
}

// Page defines model for Page.
type Page struct {
	HasMore    bool `json:"hasMore"`
	Limit      int  `json:"limit"`
	NextOffset *int `json:"nextOffset"`
	Offset     int  `json:"offset"`
}

// PathResult defines model for PathResult.
type PathResult map[string]interface{}

// PdbResult defines model for PdbResult.
type PdbResult map[string]interface{}

// PriorityResult defines model for PriorityResult.
type PriorityResult map[string]interface{}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	// Sql SELECT <*|count(*)> FROM <table> [WHERE k = v [AND ...]] [LIMIT n] [OFFSET n]
	Sql string `json:"sql"`
}

// ResolvedResource defines model for ResolvedResource.
type ResolvedResource struct {
	HashedID string  `json:"hashedID"`
	Name     string  `json:"name"`
	Term     string  `json:"term"`
	Type     *string `json:"type"`
}

// ScalingResult defines model for ScalingResult.
type ScalingResult map[string]interface{}

// ServiceTreeResult defines model for ServiceTreeResult.
type ServiceTreeResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   ServiceTreeResultScope   `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// ServiceTreeResultScope defines model for ServiceTreeResult.Scope.
type ServiceTreeResultScope string

// SharedCause defines model for SharedCause.
type SharedCause struct {
	Affected  int     `json:"affected"`
	Name      string  `json:"name"`
	Namespace *string `json:"namespace"`
}

// SharedConfigResult defines model for SharedConfigResult.
type SharedConfigResult map[string]interface{}

// SloResult defines model for SloResult.
type SloResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   SloResultScope           `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// SloResultScope defines model for SloResult.Scope.
type SloResultScope string

// SpofResult defines model for SpofResult.
type SpofResult struct {
	Filter map[string]interface{}   `json:"filter"`
	Items  []map[string]interface{} `json:"items"`
	Kind   string                   `json:"kind"`
}

// StorageResult defines model for StorageResult.
type StorageResult map[string]interface{}

// TenancyResult defines model for TenancyResult.
type TenancyResult map[string]interface{}

// TopologyResult defines model for TopologyResult.
type TopologyResult map[string]interface{}

// ProjectId defines model for ProjectId.
type ProjectId = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// AskGraphJSONRequestBody defines body for AskGraph for application/json ContentType.
type AskGraphJSONRequestBody = AskRequest

// AskProjectGraphJSONRequestBody defines body for AskProjectGraph for application/json ContentType.
type AskProjectGraphJSONRequestBody = AskRequest

// QueryProjectGraphJSONRequestBody defines body for QueryProjectGraph for application/json ContentType.
type QueryProjectGraphJSONRequestBody = QueryRequest

// QueryGraphJSONRequestBody defines body for QueryGraph for application/json ContentType.
type QueryGraphJSONRequestBody = QueryRequest
