// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package openapi

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AccessResultDirection.
const (
	Object  AccessResultDirection = "object"
	Subject AccessResultDirection = "subject"
)

// Valid indicates whether the value is a known member of the AccessResultDirection enum.
func (e AccessResultDirection) Valid() bool {
	switch e {
	case Object:
		return true
	case Subject:
		return true
	default:
		return false
	}
}

// Defines values for AskResultIntent.
const (
	AskResultIntentAccess       AskResultIntent = "access"
	AskResultIntentAlertcause   AskResultIntent = "alertcause"
	AskResultIntentAlertimpact  AskResultIntent = "alertimpact"
	AskResultIntentAlerts       AskResultIntent = "alerts"
	AskResultIntentAudit        AskResultIntent = "audit"
	AskResultIntentBlast        AskResultIntent = "blast"
	AskResultIntentCalls        AskResultIntent = "calls"
	AskResultIntentCascade      AskResultIntent = "cascade"
	AskResultIntentCommoncause  AskResultIntent = "commoncause"
	AskResultIntentConnections  AskResultIntent = "connections"
	AskResultIntentCoverage     AskResultIntent = "coverage"
	AskResultIntentDatastore    AskResultIntent = "datastore"
	AskResultIntentDeployimpact AskResultIntent = "deployimpact"
	AskResultIntentDeployments  AskResultIntent = "deployments"
	AskResultIntentEvents       AskResultIntent = "events"
	AskResultIntentExposure     AskResultIntent = "exposure"
	AskResultIntentExternaldep  AskResultIntent = "externaldep"
	AskResultIntentFailures     AskResultIntent = "failures"
	AskResultIntentFlow         AskResultIntent = "flow"
	AskResultIntentHotspots     AskResultIntent = "hotspots"
	AskResultIntentImage        AskResultIntent = "image"
	AskResultIntentIncident     AskResultIntent = "incident"
	AskResultIntentInventory    AskResultIntent = "inventory"
	AskResultIntentMonitor      AskResultIntent = "monitor"
	AskResultIntentNodes        AskResultIntent = "nodes"
	AskResultIntentOrphans      AskResultIntent = "orphans"
	AskResultIntentPath         AskResultIntent = "path"
	AskResultIntentServicetree  AskResultIntent = "servicetree"
	AskResultIntentSharedconfig AskResultIntent = "sharedconfig"
	AskResultIntentSlo          AskResultIntent = "slo"
	AskResultIntentSpof         AskResultIntent = "spof"
	AskResultIntentTenancy      AskResultIntent = "tenancy"
)

// Valid indicates whether the value is a known member of the AskResultIntent enum.
func (e AskResultIntent) Valid() bool {
	switch e {
	case AskResultIntentAccess:
		return true
	case AskResultIntentAlertcause:
		return true
	case AskResultIntentAlertimpact:
		return true
	case AskResultIntentAlerts:
		return true
	case AskResultIntentAudit:
		return true
	case AskResultIntentBlast:
		return true
	case AskResultIntentCalls:
		return true
	case AskResultIntentCascade:
		return true
	case AskResultIntentCommoncause:
		return true
	case AskResultIntentConnections:
		return true
	case AskResultIntentCoverage:
		return true
	case AskResultIntentDatastore:
		return true
	case AskResultIntentDeployimpact:
		return true
	case AskResultIntentDeployments:
		return true
	case AskResultIntentEvents:
		return true
	case AskResultIntentExposure:
		return true
	case AskResultIntentExternaldep:
		return true
	case AskResultIntentFailures:
		return true
	case AskResultIntentFlow:
		return true
	case AskResultIntentHotspots:
		return true
	case AskResultIntentImage:
		return true
	case AskResultIntentIncident:
		return true
	case AskResultIntentInventory:
		return true
	case AskResultIntentMonitor:
		return true
	case AskResultIntentNodes:
		return true
	case AskResultIntentOrphans:
		return true
	case AskResultIntentPath:
		return true
	case AskResultIntentServicetree:
		return true
	case AskResultIntentSharedconfig:
		return true
	case AskResultIntentSlo:
		return true
	case AskResultIntentSpof:
		return true
	case AskResultIntentTenancy:
		return true
	default:
		return false
	}
}

// Defines values for CallsResultScope.
const (
	CallsResultScopeRanked CallsResultScope = "ranked"
	CallsResultScopeTarget CallsResultScope = "target"
)

// Valid indicates whether the value is a known member of the CallsResultScope enum.
func (e CallsResultScope) Valid() bool {
	switch e {
	case CallsResultScopeRanked:
		return true
	case CallsResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for CoverageResultKind.
const (
	CoverageResultKindMonitor CoverageResultKind = "monitor"
	CoverageResultKindService CoverageResultKind = "service"
)

// Valid indicates whether the value is a known member of the CoverageResultKind enum.
func (e CoverageResultKind) Valid() bool {
	switch e {
	case CoverageResultKindMonitor:
		return true
	case CoverageResultKindService:
		return true
	default:
		return false
	}
}

// Defines values for DataStoreResultScope.
const (
	DataStoreResultScopeRanked DataStoreResultScope = "ranked"
	DataStoreResultScopeTarget DataStoreResultScope = "target"
)

// Valid indicates whether the value is a known member of the DataStoreResultScope enum.
func (e DataStoreResultScope) Valid() bool {
	switch e {
	case DataStoreResultScopeRanked:
		return true
	case DataStoreResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for DeployImpactResultScope.
const (
	DeployImpactResultScopeRanked DeployImpactResultScope = "ranked"
	DeployImpactResultScopeTarget DeployImpactResultScope = "target"
)

// Valid indicates whether the value is a known member of the DeployImpactResultScope enum.
func (e DeployImpactResultScope) Valid() bool {
	switch e {
	case DeployImpactResultScopeRanked:
		return true
	case DeployImpactResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeErrorCode.
const (
	BadRequest               ErrorEnvelopeErrorCode = "bad_request"
	Forbidden                ErrorEnvelopeErrorCode = "forbidden"
	Internal                 ErrorEnvelopeErrorCode = "internal"
	NotFound                 ErrorEnvelopeErrorCode = "not_found"
	PayloadTooLarge          ErrorEnvelopeErrorCode = "payload_too_large"
	ProjectGraphUnconfigured ErrorEnvelopeErrorCode = "project_graph_unconfigured"
	ProjectRequired          ErrorEnvelopeErrorCode = "project_required"
	Timeout                  ErrorEnvelopeErrorCode = "timeout"
	Unauthorized             ErrorEnvelopeErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorCode enum.
func (e ErrorEnvelopeErrorCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case Forbidden:
		return true
	case Internal:
		return true
	case NotFound:
		return true
	case PayloadTooLarge:
		return true
	case ProjectGraphUnconfigured:
		return true
	case ProjectRequired:
		return true
	case Timeout:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for ExposureResultDirection.
const (
	ExposureResultDirectionIngress  ExposureResultDirection = "ingress"
	ExposureResultDirectionWorkload ExposureResultDirection = "workload"
)

// Valid indicates whether the value is a known member of the ExposureResultDirection enum.
func (e ExposureResultDirection) Valid() bool {
	switch e {
	case ExposureResultDirectionIngress:
		return true
	case ExposureResultDirectionWorkload:
		return true
	default:
		return false
	}
}

// Defines values for ExternalDepResultScope.
const (
	ExternalDepResultScopeRanked ExternalDepResultScope = "ranked"
	ExternalDepResultScopeTarget ExternalDepResultScope = "target"
)

// Valid indicates whether the value is a known member of the ExternalDepResultScope enum.
func (e ExternalDepResultScope) Valid() bool {
	switch e {
	case ExternalDepResultScopeRanked:
		return true
	case ExternalDepResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for FlowResultScope.
const (
	FlowResultScopeRanked FlowResultScope = "ranked"
	FlowResultScopeTarget FlowResultScope = "target"
)

// Valid indicates whether the value is a known member of the FlowResultScope enum.
func (e FlowResultScope) Valid() bool {
	switch e {
	case FlowResultScopeRanked:
		return true
	case FlowResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for GraphEdgeDirection.
const (
	Downstream GraphEdgeDirection = "downstream"
	Upstream   GraphEdgeDirection = "upstream"
)

// Valid indicates whether the value is a known member of the GraphEdgeDirection enum.
func (e GraphEdgeDirection) Valid() bool {
	switch e {
	case Downstream:
		return true
	case Upstream:
		return true
	default:
		return false
	}
}

// Defines values for HotspotsResultDimension.
const (
	Namespace HotspotsResultDimension = "namespace"
	Resource  HotspotsResultDimension = "resource"
)

// Valid indicates whether the value is a known member of the HotspotsResultDimension enum.
func (e HotspotsResultDimension) Valid() bool {
	switch e {
	case Namespace:
		return true
	case Resource:
		return true
	default:
		return false
	}
}

// Defines values for ImageResultMode.
const (
	ImageResultModeByimage  ImageResultMode = "byimage"
	ImageResultModeHygiene  ImageResultMode = "hygiene"
	ImageResultModeRanked   ImageResultMode = "ranked"
	ImageResultModeWorkload ImageResultMode = "workload"
)

// Valid indicates whether the value is a known member of the ImageResultMode enum.
func (e ImageResultMode) Valid() bool {
	switch e {
	case ImageResultModeByimage:
		return true
	case ImageResultModeHygiene:
		return true
	case ImageResultModeRanked:
		return true
	case ImageResultModeWorkload:
		return true
	default:
		return false
	}
}

// Defines values for OrphansResultKind.
const (
	OrphansResultKindConfigmap      OrphansResultKind = "configmap"
	OrphansResultKindReplicaset     OrphansResultKind = "replicaset"
	OrphansResultKindRole           OrphansResultKind = "role"
	OrphansResultKindServiceaccount OrphansResultKind = "serviceaccount"
)

// Valid indicates whether the value is a known member of the OrphansResultKind enum.
func (e OrphansResultKind) Valid() bool {
	switch e {
	case OrphansResultKindConfigmap:
		return true
	case OrphansResultKindReplicaset:
		return true
	case OrphansResultKindRole:
		return true
	case OrphansResultKindServiceaccount:
		return true
	default:
		return false
	}
}

// Defines values for ServiceTreeResultScope.
const (
	ServiceTreeResultScopeRanked ServiceTreeResultScope = "ranked"
	ServiceTreeResultScopeTarget ServiceTreeResultScope = "target"
)

// Valid indicates whether the value is a known member of the ServiceTreeResultScope enum.
func (e ServiceTreeResultScope) Valid() bool {
	switch e {
	case ServiceTreeResultScopeRanked:
		return true
	case ServiceTreeResultScopeTarget:
		return true
	default:
		return false
	}
}

// Defines values for SloResultScope.
const (
	Ranked SloResultScope = "ranked"
	Target SloResultScope = "target"
)

// Valid indicates whether the value is a known member of the SloResultScope enum.
func (e SloResultScope) Valid() bool {
	switch e {
	case Ranked:
		return true
	case Target:
		return true
	default:
		return false
	}
}

// Defines values for SpofResultKind.
const (
	SpofResultKindConfigmap      SpofResultKind = "configmap"
	SpofResultKindNode           SpofResultKind = "node"
	SpofResultKindServiceaccount SpofResultKind = "serviceaccount"
)

// Valid indicates whether the value is a known member of the SpofResultKind enum.
func (e SpofResultKind) Valid() bool {
	switch e {
	case SpofResultKindConfigmap:
		return true
	case SpofResultKindNode:
		return true
	case SpofResultKindServiceaccount:
		return true
	default:
		return false
	}
}

// AccessResult defines model for AccessResult.
type AccessResult struct {
	Direction AccessResultDirection `json:"direction"`
	Roles     []struct {
		Namespace *string `json:"namespace"`
		Role      string  `json:"role"`
		Via       *string `json:"via"`
	} `json:"roles"`
	ServiceAccounts []string `json:"serviceAccounts"`
	Subjects        []struct {
		Namespace      *string  `json:"namespace"`
		Pods           int      `json:"pods"`
		ServiceAccount string   `json:"serviceAccount"`
		Via            *string  `json:"via"`
		Workloads      []string `json:"workloads"`
	} `json:"subjects"`
}

// AccessResultDirection defines model for AccessResult.Direction.
type AccessResultDirection string

// AlertCauseResult defines model for AlertCauseResult.
type AlertCauseResult struct {
	Changes        []map[string]interface{} `json:"changes"`
	FiringCount    int                      `json:"firingCount"`
	FiringMonitors []string                 `json:"firingMonitors"`
	Namespace      *string                  `json:"namespace"`
	Target         string                   `json:"target"`
	Workload       *string                  `json:"workload"`
}

// AlertImpactResult defines model for AlertImpactResult.
type AlertImpactResult struct {
	Counts    map[string]interface{}   `json:"counts"`
	Monitors  []map[string]interface{} `json:"monitors"`
	Scope     string                   `json:"scope"`
	Services  int                      `json:"services"`
	Slos      []map[string]interface{} `json:"slos"`
	Workloads int                      `json:"workloads"`
}

// AlertsResult defines model for AlertsResult.
type AlertsResult struct {
	ByState []struct {
		Count int    `json:"count"`
		State string `json:"state"`
	} `json:"byState"`
	Filter map[string]interface{}   `json:"filter"`
	Firing []map[string]interface{} `json:"firing"`
	Total  int                      `json:"total"`
}

// AskRequest defines model for AskRequest.
type AskRequest struct {
	Question string `json:"question"`
}

// AskResult defines model for AskResult.
type AskResult struct {
	Access       *AccessResult       `json:"access,omitempty"`
	AlertCause   *AlertCauseResult   `json:"alertCause,omitempty"`
	AlertImpact  *AlertImpactResult  `json:"alertImpact,omitempty"`
	Alerts       *AlertsResult       `json:"alerts,omitempty"`
	Audit        *EventFeedResult    `json:"audit,omitempty"`
	BlastRadius  *BlastRadiusResult  `json:"blastRadius,omitempty"`
	Calls        *CallsResult        `json:"calls,omitempty"`
	Cascade      *CascadeResult      `json:"cascade,omitempty"`
	CommonCause  *CommonCauseResult  `json:"commonCause,omitempty"`
	CountOnly    *bool               `json:"countOnly,omitempty"`
	Coverage     *CoverageResult     `json:"coverage,omitempty"`
	DataStore    *DataStoreResult    `json:"dataStore,omitempty"`
	DeployImpact *DeployImpactResult `json:"deployImpact,omitempty"`
	Deployments  *DeploymentsResult  `json:"deployments,omitempty"`
	Edges        *[]GraphEdge        `json:"edges,omitempty"`
	ElapsedMs    *int                `json:"elapsedMs,omitempty"`
	Events       *EventsResult       `json:"events,omitempty"`
	Exposure     *ExposureResult     `json:"exposure,omitempty"`
	ExternalDep  *ExternalDepResult  `json:"externalDep,omitempty"`
	Failures     *EventFeedResult    `json:"failures,omitempty"`
	Flow         *FlowResult         `json:"flow,omitempty"`
	Hotspots     *HotspotsResult     `json:"hotspots,omitempty"`
	Image        *ImageResult        `json:"image,omitempty"`
	Incident     *IncidentResult     `json:"incident,omitempty"`
	Intent       AskResultIntent     `json:"intent"`
	Inventory    *InventoryResult    `json:"inventory,omitempty"`
	Monitor      *MonitorResult      `json:"monitor,omitempty"`
	NodeEvents   *EventFeedResult    `json:"nodeEvents,omitempty"`
	Nodes        *[]GraphNode        `json:"nodes,omitempty"`
	Orphans      *OrphansResult      `json:"orphans,omitempty"`
	Page         *Page               `json:"page,omitempty"`
	Path         *PathResult         `json:"path,omitempty"`
	Question     string              `json:"question"`
	Resolved     *ResolvedResource   `json:"resolved,omitempty"`
	ServiceTree  *ServiceTreeResult  `json:"serviceTree,omitempty"`
	SharedConfig *SharedConfigResult `json:"sharedConfig,omitempty"`
	Slo          *SloResult          `json:"slo,omitempty"`
	Spof         *SpofResult         `json:"spof,omitempty"`
	Summary      string              `json:"summary"`
	Tenancy      *TenancyResult      `json:"tenancy,omitempty"`
}

// AskResultIntent defines model for AskResult.Intent.
type AskResultIntent string

// BlastRadiusResult defines model for BlastRadiusResult.
type BlastRadiusResult struct {
	Pods      int           `json:"pods"`
	Services  []SharedCause `json:"services"`
	Workloads []SharedCause `json:"workloads"`
}

// CallsResult defines model for CallsResult.
type CallsResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   CallsResultScope         `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// CallsResultScope defines model for CallsResult.Scope.
type CallsResultScope string

// CascadeResult defines model for CascadeResult.
type CascadeResult struct {
	ByReason []struct {
		Count  int    `json:"count"`
		Reason string `json:"reason"`
	} `json:"byReason"`
	CorrelationId string                   `json:"correlationId"`
	Root          *map[string]interface{}  `json:"root"`
	SpanSeconds   int                      `json:"spanSeconds"`
	Steps         []map[string]interface{} `json:"steps"`
	TotalEvents   int                      `json:"totalEvents"`
}

// CommonCauseResult defines model for CommonCauseResult.
type CommonCauseResult struct {
	ByDatastore []SharedCause          `json:"byDatastore"`
	ByExternal  []SharedCause          `json:"byExternal"`
	ByNode      []SharedCause          `json:"byNode"`
	ByWorkload  []SharedCause          `json:"byWorkload"`
	Events      int                    `json:"events"`
	FailingPods int                    `json:"failingPods"`
	Filter      map[string]interface{} `json:"filter"`
}

// CountByType defines model for CountByType.
type CountByType struct {
	Count int    `json:"count"`
	Type  string `json:"type"`
}

// CoverageResult defines model for CoverageResult.
type CoverageResult struct {
	Filter map[string]interface{} `json:"filter"`
	Items  []struct {
		Kind      *string `json:"kind"`
		Name      string  `json:"name"`
		Namespace *string `json:"namespace"`
	} `json:"items"`
	Kind CoverageResultKind `json:"kind"`
}

// CoverageResultKind defines model for CoverageResult.Kind.
type CoverageResultKind string

// DataStoreResult defines model for DataStoreResult.
type DataStoreResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   DataStoreResultScope     `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// DataStoreResultScope defines model for DataStoreResult.Scope.
type DataStoreResultScope string

// DeployImpactResult defines model for DeployImpactResult.
type DeployImpactResult struct {
	ByType   []CountByType            `json:"byType"`
	Filter   map[string]interface{}   `json:"filter"`
	Ranking  []map[string]interface{} `json:"ranking"`
	Recent   []EventItem              `json:"recent"`
	Rollouts int                      `json:"rollouts"`
	Scope    DeployImpactResultScope  `json:"scope"`
	Target   string                   `json:"target"`
	Total    int                      `json:"total"`
}

// DeployImpactResultScope defines model for DeployImpactResult.Scope.
type DeployImpactResultScope string

// DeploymentsResult defines model for DeploymentsResult.
type DeploymentsResult struct {
	Filter     map[string]interface{} `json:"filter"`
	Namespaces []string               `json:"namespaces"`
	Page       Page                   `json:"page"`
	Recent     []struct {
		Images []struct {
			From *string `json:"from"`
			To   *string `json:"to"`
		} `json:"images"`
		Namespace *string `json:"namespace"`
		Target    *string `json:"target"`
		Ts        string  `json:"ts"`
	} `json:"recent"`
	Total int `json:"total"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code    ErrorEnvelopeErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorEnvelopeErrorCode defines model for ErrorEnvelope.Error.Code.
type ErrorEnvelopeErrorCode string

// EventFeedResult defines model for EventFeedResult.
type EventFeedResult struct {
	ByType []CountByType          `json:"byType"`
	Filter map[string]interface{} `json:"filter"`
	Page   Page                   `json:"page"`
	Recent []EventItem            `json:"recent"`
	Total  int                    `json:"total"`
}

// EventItem defines model for EventItem.
type EventItem struct {
	Cluster    *string `json:"cluster"`
	IsRoot     bool    `json:"isRoot"`
	Namespace  *string `json:"namespace"`
	NoiseClass *string `json:"noiseClass"`
	Summary    *string `json:"summary"`
	Target     *string `json:"target"`
	TargetKind *string `json:"targetKind"`
	Ts         string  `json:"ts"`
	Type       string  `json:"type"`
}

// EventsResult defines model for EventsResult.
type EventsResult struct {
	ByType []CountByType          `json:"byType"`
	Filter map[string]interface{} `json:"filter"`
	Page   Page                   `json:"page"`
	Recent []EventItem            `json:"recent"`
	Total  int                    `json:"total"`
}

// ExposureResult defines model for ExposureResult.
type ExposureResult struct {
	Direction ExposureResultDirection  `json:"direction"`
	Exposed   bool                     `json:"exposed"`
	Ingresses []map[string]interface{} `json:"ingresses"`
	Services  []map[string]interface{} `json:"services"`
}

// ExposureResultDirection defines model for ExposureResult.Direction.
type ExposureResultDirection string

// ExternalDepResult defines model for ExternalDepResult.
type ExternalDepResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   ExternalDepResultScope   `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// ExternalDepResultScope defines model for ExternalDepResult.Scope.
type ExternalDepResultScope string

// FlowResult defines model for FlowResult.
type FlowResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   FlowResultScope          `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// FlowResultScope defines model for FlowResult.Scope.
type FlowResultScope string

// GraphEdge defines model for GraphEdge.
type GraphEdge struct {
	Direction GraphEdgeDirection `json:"direction"`
	From      string             `json:"from"`
	To        string             `json:"to"`
	Type      string             `json:"type"`
}

// GraphEdgeDirection defines model for GraphEdge.Direction.
type GraphEdgeDirection string

// GraphNode defines model for GraphNode.
type GraphNode struct {
	AnyshiftID *string `json:"anyshiftID"`
	Id         string  `json:"id"`
	Name       string  `json:"name"`
	Namespace  *string `json:"namespace"`
	Type       *string `json:"type"`
}

// HotspotsResult defines model for HotspotsResult.
type HotspotsResult struct {
	Dimension HotspotsResultDimension `json:"dimension"`
	Filter    map[string]interface{}  `json:"filter"`
	Ranking   []struct {
		Key       string  `json:"key"`
		Namespace *string `json:"namespace"`
		Total     int     `json:"total"`
	} `json:"ranking"`
}

// HotspotsResultDimension defines model for HotspotsResult.Dimension.
type HotspotsResultDimension string

// ImageResult defines model for ImageResult.
type ImageResult struct {
	ByImage  *map[string]interface{}  `json:"byImage"`
	Hygiene  *map[string]interface{}  `json:"hygiene"`
	Mode     ImageResultMode          `json:"mode"`
	Ranking  []map[string]interface{} `json:"ranking"`
	Workload *map[string]interface{}  `json:"workload"`
}

// ImageResultMode defines model for ImageResult.Mode.
type ImageResultMode string

// IncidentResult defines model for IncidentResult.
type IncidentResult struct {
	ByType        []CountByType `json:"byType"`
	Chain         []EventItem   `json:"chain"`
	CorrelationId *string       `json:"correlationId"`
	Namespaces    []string      `json:"namespaces"`
	RootCauses    []EventItem   `json:"rootCauses"`
	Roots         int           `json:"roots"`
	Total         int           `json:"total"`
}

// InventoryResult defines model for InventoryResult.
type InventoryResult struct {
	AvailableTypes []struct {
		Count int    `json:"count"`
		Label string `json:"label"`
	} `json:"availableTypes"`
	ByNamespace []struct {
		Count     int    `json:"count"`
		Namespace string `json:"namespace"`
	} `json:"byNamespace"`
	Sample []struct {
		Name      string  `json:"name"`
		Namespace *string `json:"namespace"`
	} `json:"sample"`
	Total int    `json:"total"`
	Type  string `json:"type"`
}

// MonitorResult defines model for MonitorResult.
type MonitorResult struct {
	Matched   int                      `json:"matched"`
	Monitors  []string                 `json:"monitors"`
	Nodes     []string                 `json:"nodes"`
	Services  []string                 `json:"services"`
	Slos      []string                 `json:"slos"`
	Term      string                   `json:"term"`
	Workloads []map[string]interface{} `json:"workloads"`
}

// OrphansResult defines model for OrphansResult.
type OrphansResult struct {
	Filter map[string]interface{} `json:"filter"`
	Items  []struct {
		Name      string  `json:"name"`
		Namespace *string `json:"namespace"`
	} `json:"items"`
	Kind OrphansResultKind `json:"kind"`
}

// OrphansResultKind defines model for OrphansResult.Kind.
type OrphansResultKind string

// Page defines model for Page.
type Page struct {
	HasMore    bool `json:"hasMore"`
	Limit      int  `json:"limit"`
	NextOffset *int `json:"nextOffset"`
	Offset     int  `json:"offset"`
}

// PathResult defines model for PathResult.
type PathResult struct {
	Chain []map[string]interface{} `json:"chain"`
	Found bool                     `json:"found"`
	From  *struct {
		Name string  `json:"name"`
		Term string  `json:"term"`
		Type *string `json:"type"`
	} `json:"from"`
	Hops int      `json:"hops"`
	Rels []string `json:"rels"`
	To   *struct {
		Name string  `json:"name"`
		Term string  `json:"term"`
		Type *string `json:"type"`
	} `json:"to"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	// Sql SELECT <*|count(*)> FROM <table> [WHERE k = v [AND ...]] [LIMIT n] [OFFSET n]
	Sql string `json:"sql"`
}

// ResolvedResource defines model for ResolvedResource.
type ResolvedResource struct {
	HashedID string  `json:"hashedID"`
	Name     string  `json:"name"`
	Term     string  `json:"term"`
	Type     *string `json:"type"`
}

// ServiceTreeResult defines model for ServiceTreeResult.
type ServiceTreeResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   ServiceTreeResultScope   `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// ServiceTreeResultScope defines model for ServiceTreeResult.Scope.
type ServiceTreeResultScope string

// SharedCause defines model for SharedCause.
type SharedCause struct {
	Affected  int     `json:"affected"`
	Name      string  `json:"name"`
	Namespace *string `json:"namespace"`
}

// SharedConfigResult defines model for SharedConfigResult.
type SharedConfigResult struct {
	Configmaps []string                 `json:"configmaps"`
	OwnPods    int                      `json:"ownPods"`
	Siblings   []map[string]interface{} `json:"siblings"`
}

// SloResult defines model for SloResult.
type SloResult struct {
	Ranking []map[string]interface{} `json:"ranking"`
	Scope   SloResultScope           `json:"scope"`
	Target  *map[string]interface{}  `json:"target"`
}

// SloResultScope defines model for SloResult.Scope.
type SloResultScope string

// SpofResult defines model for SpofResult.
type SpofResult struct {
	Filter map[string]interface{} `json:"filter"`
	Items  []struct {
		Name      string  `json:"name"`
		Namespace *string `json:"namespace"`
		Pods      int     `json:"pods"`
		Workloads int     `json:"workloads"`
	} `json:"items"`
	Kind SpofResultKind `json:"kind"`
}

// SpofResultKind defines model for SpofResult.Kind.
type SpofResultKind string

// TenancyResult defines model for TenancyResult.
type TenancyResult struct {
	Neighbors []map[string]interface{} `json:"neighbors"`
	Nodes     []string                 `json:"nodes"`
	OwnPods   int                      `json:"ownPods"`
}

// ProjectId defines model for ProjectId.
type ProjectId = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// AskGraphJSONRequestBody defines body for AskGraph for application/json ContentType.
type AskGraphJSONRequestBody = AskRequest

// AskProjectGraphJSONRequestBody defines body for AskProjectGraph for application/json ContentType.
type AskProjectGraphJSONRequestBody = AskRequest

// QueryProjectGraphJSONRequestBody defines body for QueryProjectGraph for application/json ContentType.
type QueryProjectGraphJSONRequestBody = QueryRequest

// QueryGraphJSONRequestBody defines body for QueryGraph for application/json ContentType.
type QueryGraphJSONRequestBody = QueryRequest
